ci(validate): use CodeQL instead of SonarCloud

diff --git a/.github/workflows/validate.yml b/.github/workflows/validate.yml
--- a/.github/workflows/validate.yml
+++ b/.github/workflows/validate.yml
@@ -61,16 +61,16 @@ jobs:
         run: npm ci
       - name: Build
         run: npm run build
-      # - name: Initialize CodeQL
-      #   if: matrix.os == 'ubuntu-latest' && matrix.node-version == '18'
-      #   uses: github/codeql-action/init@v2
-      #   with:
-      #     languages: ${{ matrix.language }}
-      # - name: Perform CodeQL Analysis
-      #   if: matrix.os == 'ubuntu-latest' && matrix.node-version == '18'
-      #   uses: github/codeql-action/analyze@v2
-      #   with:
-      #     category: /language:${{matrix.language}}
+      - name: Initialize CodeQL
+        if: matrix.os == 'ubuntu-latest' && matrix.node-version == '18'
+        uses: github/codeql-action/init@v2
+        with:
+          languages: ${{ matrix.language }}
+      - name: Perform CodeQL Analysis
+        if: matrix.os == 'ubuntu-latest' && matrix.node-version == '18'
+        uses: github/codeql-action/analyze@v2
+        with:
+          category: /language:${{matrix.language}}
 
   test:
     strategy:
@@ -95,9 +95,9 @@ jobs:
         run: npm ci
       - name: Test
         run: npm run test:coverage
-      - name: Analyze with SonarCloud
-        if: (success() || failure()) && matrix.os == 'ubuntu-latest' && matrix.node-version == '18'
-        uses: SonarSource/sonarcloud-github-action@master
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information
-          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} # Needed to push to SonarCloud
+      # - name: Analyze with SonarCloud
+      #   if: (success() || failure()) && matrix.os == 'ubuntu-latest' && matrix.node-version == '18'
+      #   uses: SonarSource/sonarcloud-github-action@master
+      #   env:
+      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information
+      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} # Needed to push to SonarCloud
